### ISSUE TITLE
Incorrect matches

### ISSUE THREAD

**Issue by parrish** [zooniverse-ui/markdownz#11]
https://github.com/zooniverse-ui/markdownz/blob/master/src/components/markdown.js#L44

https://github.com/zooniverse-ui/markdownz/blob/master/src/components/markdown.js#L46

Talk does not match subject mentions like this.  The syntax for matching a subject is `^S<id>`, e.g. `^S123`.

Likewise collection mentions are `^C<id>`.

The best way to handle this in terms of front-end links would probably be to add a redirect route at /talk/subjects/:id that looks up the project slug and redirects to the project route.

**Comment by edpaget** [comment]
Is this going to change anything that was using the old ^123 to match subject id 123?

**Comment by parrish** [comment]
The syntax in older versions of talk was just the zooniverse id (AGZ0000001).  New talk has never matched without the type prefix (otherwise you can't disambiguate the thing you're mentioning).

**Comment by edpaget** [comment]
As far I know new Talk has always matched subjects without an S prefix. In project specific Talks it can match the subject without a qualified project.

**Comment by parrish** [comment]
Nope.  It's never even been used in new talk.

**Comment by parrish** [comment]
Here's the mentioning regex if you're curious too: https://github.com/zooniverse/Talk-Api/blob/master/app/models/concerns/comment/mentioning.rb#L5-L9

**Comment by edpaget** [comment]
Yeah that's different than the help text on the Front-End, which is what I presume everyone has been using so far: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/talk/comment-help.cjsx#L11

In addition to being different than what the Front-End markdown parsers has been using, so if we change it, existing in markdown links to subjects will be broken.

**Comment by parrish** [comment]
I guess that help text has always been wrong then.  It doesn't look like anybody has mentioned a subject with either syntax at all.  If they had, I'd just migrate it.

**Comment by edpaget** [comment]
Well then no big deal either way.
